In [2]:
import numpy as np

In [26]:
np.random.randint(1, 10)

2

In [29]:
np.random.standard_normal(20).reshape(4,5)

array([[-0.3943715 ,  0.33195104,  0.35846644,  0.74488894, -0.64110516],
       [ 1.31559025,  0.57985091, -0.68184758,  0.42151133, -0.25909637],
       [-0.75417265, -1.82407994,  0.87239039,  0.82692895, -0.04626388],
       [-0.08419976, -0.28927778, -1.00454507, -0.88120469, -0.87778749]])

In [30]:
np.random.standard_normal(25).reshape(5, 5)

array([[ 1.21809644,  0.7465356 , -1.43202349, -1.69394645,  0.45003617],
       [-1.29843849,  0.99677516,  1.16878103,  1.27828892,  2.39000107],
       [ 1.35516218, -1.8416305 ,  0.10500183, -0.0153459 ,  1.15630382],
       [ 1.35752461,  0.26176401, -0.70752432,  0.79759233,  0.7461147 ],
       [-0.59654717, -0.13459872,  0.00295839, -0.01450619, -0.72143099]])

In [3]:
np.random.standard_normal(49).reshape(7, 7)

array([[ 0.31217998,  0.46814704,  1.5601521 , -1.71966036,  0.85732391,
        -0.55470696,  2.10875169],
       [-0.62693093,  1.70103257, -0.57822826,  0.65729103, -0.5058359 ,
        -0.17727755,  0.45717829],
       [-0.23596078,  1.65562212, -0.5175489 ,  0.10635553,  0.78247417,
         2.84048786, -0.13540658],
       [ 1.01469098, -1.89628787,  1.00289306, -3.27657734, -0.90993035,
         0.59280094, -0.8310904 ],
       [-0.95680305, -0.78648814,  1.10107652, -0.01679362,  0.04254964,
        -0.70360548, -0.02109528],
       [ 0.15953392,  0.36511152,  2.23451836, -0.9964162 , -1.7810945 ,
         0.61905046, -0.31547054],
       [-1.05967383, -0.59034689,  1.77046308,  1.37377727, -0.38645167,
         0.51917233, -1.21160998]])